### ISSUE TITLE
how run it locally?

### ISSUE THREAD

**Issue by jujes** [OpenPress/openpress#2]
Hi, some documentation for deploy using docker and run locally?
thanks in advance,

**Comment by EmpireWorld** [comment]
Hi @jujes.
Thanks for the comment.

OpenPress currently is **under active development**.

You see our development board at [**here**](https://trello.com/b/9eDarpdE/openpress)

We are currently developing [**OpenPress Documentation Generator**](https://github.com/OpenPress/opdoc) and in the next step we will go to create OpenPress itself.

So you can watch this repo for any further updates or you can give me your email.

Thanks.
Best Regards
